import React, { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import mealDatabase from './MealDatabase'; // Import the meal database
import { FaCoffee, FaLeaf, FaUtensils } from 'react-icons/fa'; // Importing icons for better visuals

  const translations = {
    ENG: {
      menuTitle: 'Menu for You',
      generatingMealPlan: 'Generating your meal plan...',
      reGenerateMeals: 'Re-Generate Meals',
      breakfast: 'Breakfast',
      lunch: 'Lunch',
      dinner: 'Dinner',
      flavorText: 'Enjoy your meals!',
      mealDetails: 'Ingredients: {ingredients}, Quantity: {quantity}g, Energy: {totalEnergy} kcal',
      acaiBowl: 'Acai Bowl',
      almondButterToast: 'Almond Butter Toast',
      appleCinnamonOatmeal: 'Apple Cinnamon Oatmeal',
      appleCinnamonOvernightOats: 'Apple Cinnamon Overnight Oats',
      avocadoToast: 'Avocado Toast',
      baconEggBreakfastBowl: 'Bacon Egg Breakfast Bowl',
      bagelWithLox: 'Bagel with Lox',
      bakedEggsWithSpinach: 'Baked Eggs with Spinach',
      bananaPancakes: 'Banana Pancakes',
      berryQuinoaSalad: 'Berry Quinoa Salad',
      berrySmoothieBowl: 'Berry Smoothie Bowl',
      blueberryMuffin: 'Blueberry Muffin',
      breakfastBowl: 'Breakfast Bowl',
      breakfastBurrito: 'Breakfast Burrito',
      breakfastCasserole: 'Breakfast Casserole',
      breakfastCrepes: 'Breakfast Crepes',
      breakfastEggsAndSausage: 'Breakfast Eggs and Sausage',
      breakfastEggsBenedict: 'Breakfast Eggs Benedict',
      breakfastFriedRice: 'Breakfast Fried Rice',
      breakfastFruitSalad: 'Breakfast Fruit Salad',
      breakfastGranolaBars: 'Breakfast Granola Bars',
      breakfastHashBowl: 'Breakfast Hash Bowl',
      breakfastPasta: 'Breakfast Pasta',
      breakfastPitaPocket: 'Breakfast Pita Pocket',
      breakfastQuiche: 'Breakfast Quiche',
      breakfastQuinoa: 'Breakfast Quinoa',
      breakfastQuinoaBowl: 'Breakfast Quinoa Bowl',
      breakfastSandwich: 'Breakfast Sandwich',
      breakfastSmoothie: 'Breakfast Smoothie',
      breakfastStuffedPeppers: 'Breakfast Stuffed Peppers',
      breakfastTacos: 'Breakfast Tacos',
      breakfastTofuScramble: 'Breakfast Tofu Scramble',
      buckwheatPorridge: 'Buckwheat Porridge',
      carrotCakeOatmeal: 'Carrot Cake Oatmeal',
      carrotZucchiniMuffins: 'Carrot Zucchini Muffins',
      chiaPudding: 'Chia Pudding',
      chiaSeedPudding: 'Chia Seed Pudding',
      chocolateChiaPudding: 'Chocolate Chia Pudding',
      chocolateChipMuffins: 'Chocolate Chip Muffins',
      chocolateChipPancakes: 'Chocolate Chip Pancakes',
      chocolateProteinPancakes: 'Chocolate Protein Pancakes',
      chocolateProteinShake: 'Chocolate Protein Shake',
      cinnamonRolls: 'Cinnamon Rolls',
      coconutChiaPudding: 'Coconut Chia Pudding',
      coconutRicePudding: 'Coconut Rice Pudding',
      cornmealMush: 'Cornmeal Mush',
      cottageCheeseWithFruit: 'Cottage Cheese with Fruit',
      eggAndSpinachWrap: 'Egg and Spinach Wrap',
      eggBenedict: 'Egg Benedict',
      eggsFlorentine: 'Eggs Florentine',
      eggWhiteFrittata: 'Egg White Frittata',
      eggWhiteOmelette: 'Egg White Omelette',
      frenchToast: 'French Toast',
      frittata: 'Frittata',
      fruitAndNutBars: 'Fruit and Nut Bars',
      fruitAndNutGranola: 'Fruit and Nut Granola',
      fruitSalad: 'Fruit Salad',
      fruitSmoothie: 'Fruit Smoothie',
      granola: 'Granola',
      granolaEnergyBites: 'Granola Energy Bites',
      greekYogurtParfait: 'Greek Yogurt Parfait',
      hamEggs: 'Ham and Eggs',
      mangoChiaParfait: 'Mango Chia Parfait',
      maplePecanOatmeal: 'Maple Pecan Oatmeal',
      mixedBerryParfait: 'Mixed Berry Parfait',
      muesli: 'Muesli',
      mushroomQuinoaBreakfast: 'Mushroom Quinoa Breakfast',
      nutButterBananaToast: 'Nut Butter Banana Toast',
      nutellaStuffedPancakes: 'Nutella Stuffed Pancakes',
      nuttyGranolaBars: 'Nutty Granola Bars',
      oatmeal: 'Oatmeal',
      oatmealBreakfastCookies: 'Oatmeal Breakfast Cookies',
      oatmealCookies: 'Oatmeal Cookies',
      oatmealFruitBowl: 'Oatmeal Fruit Bowl',
      oatmealFruitCups: 'Oatmeal Fruit Cups',
      orangeAlmondGranola: 'Orange Almond Granola',
      overnightOats: 'Overnight Oats',
      pancakes: 'Pancakes',
      peanutButterBananaSmoothie: 'Peanut Butter Banana Smoothie',
      peanutButterSmoothie: 'Peanut Butter Smoothie',
      poachedEggs: 'Poached Eggs',
      proteinPancakes: 'Protein Pancakes',
      pumpkinPancakes: 'Pumpkin Pancakes',
      quiche: 'Quiche',
      quinoaBreakfastBowl: 'Quinoa Breakfast Bowl',
      ricePudding: 'Rice Pudding',
      ricottaToastWithBerries: 'Ricotta Toast with Berries',
      sausageBreakfastBowl: 'Sausage Breakfast Bowl',
      savoryBreakfastBowl: 'Savory Breakfast Bowl',
      savoryBreakfastPancakes: 'Savory Breakfast Pancakes',
      savoryScones: 'Savory Scones',
      scrambledEggs: 'Scrambled Eggs',
      shakshuka: 'Shakshuka',
      smoothie: 'Smoothie',
      smoothieBowl: 'Smoothie Bowl',
      spicedAppleCiderDonuts: 'Spiced Apple Cider Donuts',
      spicyAvocadoEggToast: 'Spicy Avocado Egg Toast',
      spicyTofuScramble: 'Spicy Tofu Scramble',
      spinachAndFetaWrap: 'Spinach and Feta Wrap',
      spinachFetaEggWrap: 'Spinach Feta Egg Wrap',
      spinachFetaQuiche: 'Spinach Feta Quiche',
      spinachSmoothie: 'Spinach Smoothie',
      strawberryBananaSmoothie: 'Strawberry Banana Smoothie',
      sweetPotatoFrittata: 'Sweet Potato Frittata',
      sweetPotatoHash: 'Sweet Potato Hash',
      sweetPotatoPancakes: 'Sweet Potato Pancakes',
      tropicalFruitSalad: 'Tropical Fruit Salad',
      tropicalSmoothie: 'Tropical Smoothie',
      veggieBreakfastWrap: 'Veggie Breakfast Wrap',
      veggieOmelette: 'Veggie Omelette',
      wholeGrainToastWithAvocado: 'Whole Grain Toast with Avocado',
      wholeWheatBagel: 'Whole Wheat Bagel',
      yogurtParfait: 'Yogurt Parfait',
      zucchiniBread: 'Zucchini Bread',
      zucchiniFritters: 'Zucchini Fritters',
      almondMilkUnsweetened: 'Almond Milk (Unsweetened)',
      avocadoSmoothie: 'Avocado Smoothie',
      blackCoffee: 'Black Coffee',
      blueberryChiaSmoothie: 'Blueberry Chia Smoothie',
      carrotJuice: 'Carrot Juice',
      chiaSeedWater: 'Chia Seed Water',
      coconutWater: 'Coconut Water',
      gingerTea: 'Ginger Tea',
      greenSmoothie: 'Green Smoothie',
      honeyLemonWater: 'Honey Lemon Water',
      mangoSmoothie: 'Mango Smoothie',
      matchaLatte: 'Matcha Latte',
      oatMilkUnsweetened: 'Oat Milk (Unsweetened)',
      orangeJuice: 'Orange Juice',
      peppermintTea: 'Peppermint Tea',
      pomegranateJuice: 'Pomegranate Juice',
      soyMilk: 'Soy Milk',
      strawberrySmoothie: 'Strawberry Smoothie',
      turmericLatte: 'Turmeric Latte',
      watermelonJuice: 'Watermelon Juice',
      almondMilkYogurt: 'Almond Milk Yogurt',
      asiagoCheese: 'Asiago Cheese',
      blueberryYogurt: 'Blueberry Yogurt',
      blueCheese: 'Blue Cheese',
      brieCheese: 'Brie Cheese',
      burrataCheese: 'Burrata Cheese',
      cabraAlVinoCheese: 'Cabra al Vino Cheese',
      camembertCheese: 'Camembert Cheese',
      cantalCheese: 'Cantal Cheese',
      casuMarzuCheese: 'Casu Marzu Cheese',
      chabichouCheese: 'Chabichou Cheese',
      cheddarCheese: 'Cheddar Cheese',
      cheshireCheese: 'Cheshire Cheese',
      chevreCheese: 'Chevre Cheese',
      chocolateYogurt: 'Chocolate Yogurt',
      coconutMilkYogurt: 'Coconut Milk Yogurt',
      comteCheese: 'Comté Cheese',
      cotijaCheese: 'Cotija Cheese',
      cottegeCheese: 'Cottage Cheese',
      crottinCheese: 'Crottin Cheese',
      emmentalCheese: 'Emmental Cheese',
      fetaCheese: 'Feta Cheese',
      gorgonzolaCheese: 'Gorgonzola Cheese',
      goudaCheese: 'Gouda Cheese',
      gruyereCheese: 'Gruyère Cheese',
      halloumiCheese: 'Halloumi Cheese',
      havartiCheese: 'Havarti Cheese',
      honeyGreekYogurt: 'Honey Greek Yogurt',
      kefir: 'Kefir',
      langresCheese: 'Langres Cheese',
      leerdammerCheese: 'Leerdammer Cheese',
      limburgerCheese: 'Limburger Cheese',
      livarotCheese: 'Livarot Cheese',
      lowFatYogurt: 'Low-Fat Yogurt',
      manchegoCheese: 'Manchego Cheese',
      mangoYogurt: 'Mango Yogurt',
      mimoletteCheese: 'Mimolette Cheese',
      mozzarellaCheese: 'Mozzarella Cheese',
      muensterCheese: 'Muenster Cheese',
      neufchâtelCheese: 'Neufchâtel Cheese',
      nevatCheese: 'Nevat Cheese',
      parmesanCheese: 'Parmesan Cheese',
      peachYogurt: 'Peach Yogurt',
      pecorinoCheese: 'Pecorino Cheese',
      plainGreekYogurt: 'Plain Greek Yogurt',
      quarkCheese: 'Quark Cheese',
      quesoFrescoCheese: 'Queso Fresco Cheese',
      raspberryYogurt: 'Raspberry Yogurt',
      ricottaCheese: 'Ricotta Cheese',
      roquefortCheese: 'Roquefort Cheese',
      saintNectaireCheese: 'Saint-Nectaire Cheese',
      smokedGouda: 'Smoked Gouda',
      sourCreamCheese: 'Sour Cream Cheese',
      soyYogurt: 'Soy Yogurt',
      stinkingBishopCheese: 'Stinking Bishop Cheese',
      strawberryYogurt: 'Strawberry Yogurt',
      taleggioCheese: 'Taleggio Cheese',
      tommeDeSavoieCheese: 'Tomme de Savoie Cheese',
      vacherinCheese: 'Vacherin Cheese',
      valdeonCheese: 'Valdeón Cheese',
      vanillaYogurt: 'Vanilla Yogurt',
      wholeMilkYogurt: 'Whole Milk Yogurt',
      yorkshireBlueCheese: 'Yorkshire Blue Cheese',
      almondCake: 'Almond Cake',
      almondJoyBars: 'Almond Joy Bars',
      appleCrisp: 'Apple Crisp',
      appleCrumble: 'Apple Crumble',
      appleOatmealPancakes: 'Apple Oatmeal Pancakes',
      applePie: 'Apple Pie',
      baklava: 'Baklava',
      bananaBread: 'Banana Bread',
      bananaNutBread: 'Banana Nut Bread',
      bananaPudding: 'Banana Pudding',
      bananaSplit: 'Banana Split',
      blueberryCheesecake: 'Blueberry Cheesecake',
      blueberryPie: 'Blueberry Pie',
      brownies: 'Brownies',
      caramelAppleDumpCake: 'Caramel Apple Dump Cake',
      caramelFlan: 'Caramel Flan',
      caramelPopcorn: 'Caramel Popcorn',
      carrotCake: 'Carrot Cake',
      cheesecake: 'Cheesecake',
      cherryAlmondGranola: 'Cherry Almond Granola',
      cherryClafoutis: 'Cherry Clafoutis',
      chocolateBavarianCream: 'Chocolate Bavarian Cream',
      chocolateBrownies: 'Chocolate Brownies',
      chocolateCake: 'Chocolate Cake',
      chocolateChipCookies: 'Chocolate Chip Cookies',
      chocolateCoconutBalls: 'Chocolate Coconut Balls',
      chocolateCoconutPie: 'Chocolate Coconut Pie',
      chocolateCoveredStrawberries: 'Chocolate Covered Strawberries',
      chocolateDippedBananas: 'Chocolate Dipped Bananas',
      chocolateEclair: 'Chocolate Eclair',
      chocolateFondue: 'Chocolate Fondue',
      chocolateFudgeCake: 'Chocolate Fudge Cake',
      chocolateMilkshake: 'Chocolate Milkshake',
      chocolateMintBrownies: 'Chocolate Mint Brownies',
      chocolateMousse: 'Chocolate Mousse',
      chocolatePavlova: 'Chocolate Pavlova',
      chocolatePeanutButterBars: 'Chocolate Peanut Butter Bars',
      chocolatePecanPie: 'Chocolate Pecan Pie',
      chocolatePudding: 'Chocolate Pudding',
      chocolateRaspberryTrifle: 'Chocolate Raspberry Trifle',
      chocolateSouffle: 'Chocolate Souffle',
      chocolateTart: 'Chocolate Tart',
      churros: 'Churros',
      coconutCreamPie: 'Coconut Cream Pie',
      coconutMacaroons: 'Coconut Macaroons',
      custard: 'Custard',
      eclair: 'Eclair',
      frozenYogurt: 'Frozen Yogurt',
      fruitTart: 'Fruit Tart',
      fudgeBrownies: 'Fudge Brownies',
      gelato: 'Gelato',
      gingerbread: 'Gingerbread',
      gingerbreadCookies: 'Gingerbread Cookies',
      honeycombToffee: 'Honeycomb Toffee',
      keyLimePie: 'Key Lime Pie',
      lemonMeringuePie: 'Lemon Meringue Pie',
      macaron: 'Macaron',
      matchaGreenTeaCake: 'Matcha Green Tea Cake',
      matchaPancakes: 'Matcha Pancakes',
      moltenChocolateCake: 'Molten Chocolate Cake',
      oatmealBananaCookies: 'Oatmeal Banana Cookies',
      oatmealRaisinCookies: 'Oatmeal Raisin Cookies',
      orangeSorbet: 'Orange Sorbet',
      orangeUpsideDownCake: 'Orange Upside-Down Cake',
      pannaCotta: 'Panna Cotta',
      pannaCottaCoconut: 'Panna Cotta Coconut',
      pannaCottaVanilla: 'Panna Cotta Vanilla',
      pavlova: 'Pavlova',
      peachCobbler: 'Peach Cobbler',
      peachMelba: 'Peach Melba',
      pecanPie: 'Pecan Pie',
      profiteroles: 'Profiteroles',
      pumpkinPie: 'Pumpkin Pie',
      pumpkinSpiceLatte: 'Pumpkin Spice Latte',
      pumpkinSpicePancakes: 'Pumpkin Spice Pancakes',
      quinoaFruitBowl: 'Quinoa Fruit Bowl',
      raspberryMousse: 'Raspberry Mousse',
      raspberrySorbet: 'Raspberry Sorbet',
      redVelvetCake: 'Red Velvet Cake',
      redWinePoachedPears: 'Red Wine Poached Pears',
      snickerdoodleCookies: 'Snickerdoodle Cookies',
      stickyRiceMango: 'Sticky Rice with Mango',
      strawberryCheesecake: 'Strawberry Cheesecake',
      strawberryShortcake: 'Strawberry Shortcake',
      sweetPotatoPie: 'Sweet Potato Pie',
      tiramisu: 'Tiramisu',
      tiramisuCupcakes: 'Tiramisu Cupcakes',
      vanillaBeanIceCream: 'Vanilla Bean Ice Cream',
      vanillaCupcake: 'Vanilla Cupcake',
      vanillaIceCream: 'Vanilla Ice Cream',
      vanillaPudding: 'Vanilla Pudding',
      whiteChocolateRaspberryCheesecake: 'White Chocolate Raspberry Cheesecake',
      baconCheeseburger: 'Bacon Cheeseburger',
      bakedPotato: 'Baked Potato',
      bakedZiti: 'Baked Ziti',
      bangersAndMash: 'Bangers and Mash',
      barbecueChicken: 'Barbecue Chicken',
      beefAndBroccoli: 'Beef and Broccoli',
      beefBourgignon: 'Beef Bourgignon',
      beefRagu: 'Beef Ragu',
      beefStroganoff: 'Beef Stroganoff',
      beefTacos: 'Beef Tacos',
      blackBeanTacos: 'Black Bean Tacos',
      bltSandwich: 'BLT Sandwich',
      bolognesePasta: 'Bolognese Pasta',
      butterChicken: 'Butter Chicken',
      butternutSquashRisotto: 'Butternut Squash Risotto',
      cabbageRolls: 'Cabbage Rolls',
      carrotGingerSoup: 'Carrot Ginger Soup',
      chanaMasala: 'Chana Masala',
      chickenAdobo: 'Chicken Adobo',
      chickenAlfredo: 'Chicken Alfredo',
      chickenAndRice: 'Chicken and Rice',
      chickenCaesarSalad: 'Chicken Caesar Salad',
      chickenCurry: 'Chicken Curry',
      chickenFajitas: 'Chicken Fajitas',
      chickenKorma: 'Chicken Korma',
      chickenNoodleSoup: 'Chicken Noodle Soup',
      chickenParmesan: 'Chicken Parmesan',
      chickenPotPie: 'Chicken Pot Pie',
      chickenSchnitzel: 'Chicken Schnitzel',
      chickenSouvlaki: 'Chicken Souvlaki',
      chickenTikkaMasala: 'Chicken Tikka Masala',
      chiliConCarne: 'Chili Con Carne',
      clamChowder: 'Clam Chowder',
      coconutRice: 'Coconut Rice',
      coqAuVin: 'Coq Au Vin',
      cornChowder: 'Corn Chowder',
      creamyMushroomRisotto: 'Creamy Mushroom Risotto',
      creamySpinachPasta: 'Creamy Spinach Pasta',
      crispyDuck: 'Crispy Duck',
      curryChicken: 'Curry Chicken',
      curryTofu: 'Curry Tofu',
      eggFriedRice: 'Egg Fried Rice',
      eggplantParmesan: 'Eggplant Parmesan',
      eggSalad: 'Egg Salad',
      falafelBowl: 'Falafel Bowl',
      falafelWrap: 'Falafel Wrap',
      fishAndChips: 'Fish and Chips',
      fishTacos: 'Fish Tacos',
      friedRice: 'Fried Rice',
      garlicButterPasta: 'Garlic Butter Pasta',
      garlicPasta: 'Garlic Pasta',
      gnocchi: 'Gnocchi',
      gnocchiAlPesto: 'Gnocchi al Pesto',
      goulash: 'Goulash',
      grilledCheeseSandwich: 'Grilled Cheese Sandwich',
      grilledEggplantParmesan: 'Grilled Eggplant Parmesan',
      grilledLemonChicken: 'Grilled Lemon Chicken',
      grilledVegetableWrap: 'Grilled Vegetable Wrap',
      grilledVeggiePasta: 'Grilled Veggie Pasta',
      gyros: 'Gyros',
      jambalaya: 'Jambalaya',
      jerkChicken: 'Jerk Chicken',
      kebab: 'Kebab',
      kimchiFriedRice: 'Kimchi Fried Rice',
      lambChops: 'Lamb Chops',
      lemonButterShrimp: 'Lemon Butter Shrimp',
      lemonGarlicTilapia: 'Lemon Garlic Tilapia',
      lobsterRoll: 'Lobster Roll',
      macaroniAndCheese: 'Macaroni and Cheese',
      mediterraneanQuinoaBowl: 'Mediterranean Quinoa Bowl',
      misoRamen: 'Miso Ramen',
      mixedVegetableStirFry: 'Mixed Vegetable Stir Fry',
      moussaka: 'Moussaka',
      mushroomRisotto: 'Mushroom Risotto',
      padKrapowMoo: 'Pad Krapow Moo',
      padThai: 'Pad Thai',
      paella: 'Paella',
      pestoPasta: 'Pesto Pasta',
      phillyCheesesteak: 'Philly Cheesesteak',
      pokeBowl: 'Poke Bowl',
      porkChop: 'Pork Chop',
      pulledPorkSandwich: 'Pulled Pork Sandwich',
      quesadilla: 'Quesadilla',
      quicheLorraine: 'Quiche Lorraine',
      quinoaStuffedEggplant: 'Quinoa Stuffed Eggplant',
      ratatouille: 'Ratatouille',
      risotto: 'Risotto',
      risottoMushrooms: 'Risotto with Mushrooms',
      roastedVegetableQuinoa: 'Roasted Vegetable Quinoa',
      salmonFillet: 'Salmon Fillet',
      salmonPasta: 'Salmon Pasta',
      sausageAndMash: 'Sausage and Mash',
      seafoodPaella: 'Seafood Paella',
      seafoodRisotto: 'Seafood Risotto',
      shepherdsPie: 'Shepherd’s Pie',
      shrimpFriedRice: 'Shrimp Fried Rice',
      shrimpScampi: 'Shrimp Scampi',
      spaghettiCarbonara: 'Spaghetti Carbonara',
      spicyShrimpTacos: 'Spicy Shrimp Tacos',
      spicyTofuStirFry: 'Spicy Tofu Stir Fry',
      spinachLasagna: 'Spinach Lasagna',
      stuffedBellPeppers: 'Stuffed Bell Peppers',
      sushiRoll: 'Sushi Roll',
      sweetPotatoCasserole: 'Sweet Potato Casserole',
      sweetPotatoCurry: 'Sweet Potato Curry',
      teriyakiChicken: 'Teriyaki Chicken',
      teriyakiSalmon: 'Teriyaki Salmon',
      teriyakiShrimp: 'Teriyaki Shrimp',
      teriyakiTofu: 'Teriyaki Tofu',
      turkeyChili: 'Turkey Chili',
      turkeyMeatballs: 'Turkey Meatballs',
      veganChili: 'Vegan Chili',
      vegetableStirFry: 'Vegetable Stir Fry',
      veggieBurger: 'Veggie Burger',
      veggieLasagna: 'Veggie Lasagna',
      veggieStirFry: 'Veggie Stir Fry',
      zucchiniLasagna: 'Zucchini Lasagna',
      zucchiniNoodles: 'Zucchini Noodles',
      antipastoPlatter: 'Antipasto Platter',
      avocadoEggSalad: 'Avocado Egg Salad',
      avocadoSpringRolls: 'Avocado Spring Rolls',
      baconCheddarPotatoSkins: 'Bacon Cheddar Potato Skins',
      baconWrappedAsparagus: 'Bacon Wrapped Asparagus',
      baconWrappedDates: 'Bacon Wrapped Dates',
      beetHummus: 'Beet Hummus',
      beetrootSalad: 'Beetroot Salad',
      beetSalad: 'Beet Salad',
      bruschetta: 'Bruschetta',
      bruschettaSalad: 'Bruschetta Salad',
      butternutSquashSoup: 'Butternut Squash Soup',
      caponata: 'Caponata',
      capreseSalad: 'Caprese Salad',
      carrotHummus: 'Carrot Hummus',
      carrotSticksWithDip: 'Carrot Sticks with Dip',
      cheeseAndCrackers: 'Cheese and Crackers',
      cheesePlatter: 'Cheese Platter',
      cheeseQuesadilla: 'Cheese Quesadilla',
      cheeseStuffedPeppers: 'Cheese Stuffed Peppers',
      chickenQuesadilla: 'Chicken Quesadilla',
      chickenSatay: 'Chicken Satay',
      chickenWings: 'Chicken Wings',
      chickpeaSalad: 'Chickpea Salad',
      chiliCheeseFries: 'Chili Cheese Fries',
      coconutShrimp: 'Coconut Shrimp',
      cornFritters: 'Corn Fritters',
      crabCakes: 'Crab Cakes',
      crabPuffs: 'Crab Puffs',
      crabRangoon: 'Crab Rangoon',
      crispyTofuBites: 'Crispy Tofu Bites',
      cucumberAndHummus: 'Cucumber and Hummus',
      deviledEggs: 'Deviled Eggs',
      eggplantCaviar: 'Eggplant Caviar',
      falafel: 'Falafel',
      fruitSkewers: 'Fruit Skewers',
      garlicBread: 'Garlic Bread',
      garlicParmesanBread: 'Garlic Parmesan Bread',
      garlicParmesanMushrooms: 'Garlic Parmesan Mushrooms',
      gazpacho: 'Gazpacho',
      greekSalad: 'Greek Salad',
      grilledVegetableSkewers: 'Grilled Vegetable Skewers',
      lentilSalad: 'Lentil Salad',
      lentilSoup: 'Lentil Soup',
      loadedNachos: 'Loaded Nachos',
      mangoSalsa: 'Mango Salsa',
      marinatedOlives: 'Marinated Olives',
      meatballs: 'Meatballs',
      miniPizzas: 'Mini Pizzas',
      miniQuiches: 'Mini Quiches',
      onionSoup: 'Onion Soup',
      peaSoup: 'Pea Soup',
      potatoCroquettes: 'Potato Croquettes',
      potatoSkins: 'Potato Skins',
      prosciuttoMelon: 'Prosciutto Melon',
      pumpkinSoup: 'Pumpkin Soup',
      quinoaSalad: 'Quinoa Salad',
      quinoaTabbouleh: 'Quinoa Tabbouleh',
      roastedGarlicBread: 'Roasted Garlic Bread',
      roastedRedPepperHummus: 'Roasted Red Pepper Hummus',
      salmonSushi: 'Salmon Sushi',
      savoryCheeseScones: 'Savory Cheese Scones',
      shrimpCeviche: 'Shrimp Ceviche',
      shrimpCocktail: 'Shrimp Cocktail',
      shrimpSpringRolls: 'Shrimp Spring Rolls',
      shrimpTacos: 'Shrimp Tacos',
      smokedSalmonCanapés: 'Smoked Salmon Canapés',
      spicedSweetPotatoWedges: 'Spiced Sweet Potato Wedges',
      spicyChickenWings: 'Spicy Chicken Wings',
      spicyHummus: 'Spicy Hummus',
      spicyLentilSoup: 'Spicy Lentil Soup',
      spinachArtichokeDip: 'Spinach Artichoke Dip',
      spinachFetaPuffs: 'Spinach Feta Puffs',
      springRolls: 'Spring Rolls',
      stuffedMushrooms: 'Stuffed Mushrooms',
      stuffedPeppers: 'Stuffed Peppers',
      sweetCornFritters: 'Sweet Corn Fritters',
      sweetPotatoFries: 'Sweet Potato Fries',
      tempuraVegetables: 'Tempura Vegetables',
      tomatoBasilSoup: 'Tomato Basil Soup',
      tunaSalad: 'Tuna Salad',
      tunaTartare: 'Tuna Tartare',
      veganStuffedMushrooms: 'Vegan Stuffed Mushrooms',
      vegetableSamosas: 'Vegetable Samosas',
      vegetableSpringRolls: 'Vegetable Spring Rolls',
      vegetableSushi: 'Vegetable Sushi',
      vegetableTempura: 'Vegetable Tempura',
      watermelonFetaSalad: 'Watermelon Feta Salad',
      wildRiceSalad: 'Wild Rice Salad',
      asparagus: 'Asparagus',
      bellPepper: 'Bell Pepper',
      bitterMelon: 'Bitter Melon',
      broccoli: 'Broccoli',
      brusselsSprouts: 'Brussels Sprouts',
      butternutSquash: 'Butternut Squash',
      carrot: 'Carrot',
      cauliflower: 'Cauliflower',
      cucumber: 'Cucumber',
      daikon: 'Daikon',
      eggplant: 'Eggplant',
      fennel: 'Fennel',
      kale: 'Kale',
      lettuce: 'Lettuce',
      mustardGreens: 'Mustard Greens',
      parsnip: 'Parsnip',
      radish: 'Radish',
      seaweed: 'Seaweed',
      spinach: 'Spinach',
      sweetPotato: 'Sweet Potato',
      swissChard: 'Swiss Chard',
      tomato: 'Tomato',
      turnip: 'Turnip',
      waterSpinach: 'Water Spinach',
      zucchini: 'Zucchini',
      apple: 'Apple',
      banana: 'Banana',
      blueberry: 'Blueberry',
      carambola: 'Carambola',
      cherries: 'Cherries',
      cloudberry: 'Cloudberry',
      custardApple: 'Custard Apple',
      dragonFruit: 'Dragon Fruit',
      feijoa: 'Feijoa',
      fig: 'Fig',
      grapefruit: 'Grapefruit',
      guava: 'Guava',
      jackfruit: 'Jackfruit',
      kiwi: 'Kiwi',
      kumquat: 'Kumquat',
      lychee: 'Lychee',
      mango: 'Mango',
      mulberry: 'Mulberry',
      orange: 'Orange',
      papaya: 'Papaya',
      passionFruit: 'Passion Fruit',
      pear: 'Pear',
      persimmon: 'Persimmon',
      pineapple: 'Pineapple',
      pomegranate: 'Pomegranate',
      rambutan: 'Rambutan',
      raspberries: 'Raspberries',
      sapodilla: 'Sapodilla',
      starfruit: 'Starfruit',
      strawberry: 'Strawberry',
      watermelon: 'Watermelon',
      Acai: 'Acai puree',
      Acid: 'Acid',
      Alcohol: 'Alcohol',
      Almond: 'Almond milk',
      AlmondMilk: 'Almond Milk',
      Apple: 'Apple',
      ArborioRice: 'Arborio Rice',
      Artichokes: 'Artichokes',
      Asparagus: 'Asparagus',
      AssortedCheeses: 'Assorted Cheeses',
      AssortedVegetables: 'Assorted Vegetables',
      Avocado: 'Avocado',
      AvocadoOil: 'Avocado Oil',
      Bacon: 'Bacon',
      Bagel: 'Bagel',
      BakingPowder: 'Baking Powder',
      BacterialCultures: 'Bacterial cultures',
      Banana: 'Banana',
      BarbecueSauce: 'Barbecue Sauce',
      Barley: 'Barley',
      Basil: 'Basil',
      Batter: 'Batter',
      BayLeaf: 'Bay Leaf',
      BeanSprouts: 'Bean Sprouts',
      Beans: 'Beans',
      Beef: 'Beef',
      BeefBroth: 'Beef Broth',
      Beets: 'Beets',
      BellPeppers: 'Bell Peppers',
      Berries: 'Berries',
      BitterMelon: 'Bitter Melon',
      BlackBeans: 'Black Beans',
      BlackPepper: 'Black pepper',
      Blueberries: 'Blueberries',
      Bread: 'Bread',
      Breadcrumbs: 'Bread Crumbs',
      Breading: 'Breading',
      Broccoli: 'Broccoli',
      Broth: 'Broth',
      BrusselsSprouts: 'Brussels Sprouts',
      Buckwheat: 'Buckwheat',
      Bun: 'Bun',
      Butter: 'Butter',
      Buttermilk: 'Buttermilk',
      ButternutSquash: 'Butternut Squash',
      CaesarDressing: 'Caesar Dressing',
      Cabbage: 'Cabbage',
      Capers: 'Capers',
      Carambola: 'Carambola',
      Carrot: 'Carrot',
      Cauliflower: 'Cauliflower',
      Celery: 'Celery',
      Cereal: 'Cereal',
      CheddarCheese: 'Cheddar cheese',
      Cheese: 'Cheese',
      Cherries: 'Cherries',
      Chickpeas: 'Chickpeas',
      Chicken: 'Chicken',
      Chili: 'Chili',
      ChiliPowder: 'Chili Powder',
      Chocolate: 'Chocolate',
      Chia: 'Chia seeds',
      Cider: 'Cider',
      Cilantro: 'Cilantro',
      Cinnamon: 'Cinnamon',
      Clams: 'Clams',
      Cloudberry: 'Cloudberry',
      Cocoa: 'Cocoa',
      Coconut: 'Coconut',
      CoconutMilk: 'Coconut Milk',
      CoconutOil: 'Coconut Oil',
      CocktailSauce: 'Cocktail Sauce',
      Coffee: 'Coffee',
      Coleslaw: 'Coleslaw',
      Corn: 'Corn',
      Cornstarch: 'Cornstarch',
      Couscous: 'Couscous',
      CrabMeat: 'Crab Meat',
      Crackers: 'Crackers',
      Cream: 'Cream',
      CreamCheese: 'Cream Cheese',
      Croutons: 'Croutons',
      Cucumber: 'Cucumber',
      Cumin: 'Cumin',
      Curry: 'Curry',
      CustardApple: 'Custard Apple',
      DriedFruits: 'Dried fruits',
      Daikon: 'Daikon',
      DarkChocolate: 'Dark Chocolate',
      Dates: 'Dates',
      DragonFruit: 'Dragon Fruit',
      Dressings: 'Dressings',
      Duck: 'Duck',
      Egg: 'Egg',
      Eggplant: 'Eggplant',
      Feijoa: 'Feijoa',
      Fennel: 'Fennel',
      Fig: 'Fig',
      Fish: 'Fish',
      Flour: 'Flour',
      Fries: 'Fries',
      Fruits: 'Fruit',
      Garlic: 'Garlic',
      Gelatin: 'Gelatin',
      Ginger: 'Ginger',
      Gnocchi: 'Gnocchi',
      GoatsMilk: 'Goat\'s milk',
      Grapefruit: 'Grapefruit',
      Grapes: 'Grapes',
      Granola: 'Granola',
      Gravy: 'Gravy',
      GreekYogurt: 'Greek yogurt',
      GreenOnions: 'Green Onions',
      GrilledVegetables: 'Grilled Vegetables',
      GroundMeat: 'Ground Meat',
      Guava: 'Guava',
      Ham: 'Ham',
      Herbs: 'Herbs',
      HoagieRoll: 'Hoagie Roll',
      Hollandaise: 'Hollandaise sauce',
      Honey: 'Honey',
      HotDogBun: 'Hot Dog Bun',
      HotSauce: 'Hot Sauce',
      Hummus: 'Hummus',
      IceCream: 'Ice Cream',
      Insect: 'Live insect larvae',
      Jackfruit: 'Jackfruit',
      Jalapeños: 'Jalapeños',
      JerkMarinade: 'Jerk Marinade',
      Juices: 'Juice',
      Kale: 'Kale',
      Kimchi: 'Kimchi',
      Kiwi: 'Kiwi',
      Kumquat: 'Kumquat',
      Lamb: 'Lamb',
      Leeks: 'Leek',
      Lemon: 'Lemon',
      Lettuce: 'Lettuce',
      Lentils: 'Lentils',
      LimeJuice: 'Lime Juice',
      Lobster: 'Lobster',
      Lychee: 'Lychee',
      Macaroni: 'Macaroni',
      Mango: 'Mango',
      MapleSyrup: 'Maple Syrup',
      Maplesyrup: 'Maple syrup',
      MarinaraSauce: 'Marinara Sauce',
      MarinatedVegetables: 'Marinated Vegetables',
      Marshmallows: 'Marshmallows',
      Mayonnaise: 'Mayonnaise',
      Matcha: 'Matcha Powder',
      Melon: 'Melon',
      Milk: 'Milk',
      Mint: 'Mint',
      Miso: 'Miso',
      MixedFruits: 'Mixed Fruits',
      MixedVegetables: 'Mixed Vegetables',
      Mixedberries: 'Mixed berries',
      Mixedfruit: 'Mixed fruit',
      Mixedfruits: 'Mixed fruits (Apples, Berries, Oranges)',
      Mozzarella: 'Mozzarella',
      Muffin: 'English muffin',
      Muffins: 'Muffin',
      Mulberry: 'Mulberry',
      Mushrooms: 'Mushrooms',
      Mussels: 'Mussels',
      Mustard: 'Mustard',
      Noodles: 'Noodles',
      Nutmeg: 'Nutmeg',
      Nuts: 'Nuts',
      Oatmeal: 'Oatmeal',
      Oats: 'Oats',
      Oil: 'Oil',
      Olives: 'Olives',
      Onions: 'Onion',
      Oranges: 'Oranges',
      Oregano: 'Oregano',
      Oysters: 'Oysters',
      Pancakes: 'Pancakes',
      Papaya: 'Papaya',
      Paprika: 'Paprika',
      Parmesan: 'Parmesan',
      Parsley: 'Parsley',
      Parsnips: 'Parsnips',
      PassionFruit: 'Passion Fruit',
      Pasta: 'Pasta',
      PastaSauce: 'Pasta Sauce',
      Pastrami: 'Pastrami',
      Peaches: 'Peaches',
      Peanut: 'Peanuts',
      PeanutButter: 'Peanut Butter',
      Pear: 'Pears',
      Pecans: 'Pecans',
      Peppers: 'Peppers',
      Pepperoni: 'Pepperoni',
      Pickles: 'Pickles',
      Pineapple: 'Pineapple',
      Pita: 'Pita',
      PizzaDough: 'Pizza Dough',
      Plantain: 'Plantain',
      Plums: 'Plums',
      Pomegranate: 'Pomegranate',
      Popcorn: 'Popcorn',
      Pork: 'Pork',
      Prawns: 'Prawns',
      Pretzels: 'Pretzels',
      PricklyPear: 'Prickly Pear',
      Prosciutto: 'Prosciutto',
      Prunes: 'Prunes',
      Pudding: 'Pudding',
      Pumpkin: 'Pumpkin',
      PumpkinSeeds: 'Pumpkin Seeds',
      QuailEggs: 'Quail eggs',
      Quinoa: 'Quinoa',
      Radicchio: 'Radicchio',
      Radishes: 'Radishes',
      Raisins: 'Raisins',
      Raspberries: 'Raspberries',
      Rice: 'Rice',
      RiceNoodles: 'Rice noodles',
      Ricotta: 'Ricotta',
      Roll: 'Roll',
      Rosemary: 'Rosemary',
      RyeBread: 'Rye Bread',
      Salad: 'Salad',
      Salt: 'Salt',
      Salsa: 'Salsa',
      Sapodilla: 'Sapodilla',
      Sausage: 'Sausage',
      Scallops: 'Scallops',
      Seaweed: 'Seaweed',
      Sesame: 'Sesame Seeds',
      Shallots: 'Shallots',
      Shellfish: 'Shellfish',
      Shrimp: 'Shrimp',
      Sorrel: 'Sorrel',
      SoySauce: 'Soy Sauce',
      Soybeans: 'Soybeans',
      Soymilk: 'Soy Milk',
      Spaghetti: 'Spaghetti',
      Spinach: 'Spinach',
      Squid: 'Squid',
      SquidInk: 'Squid Ink',
      Starfruit: 'Starfruit',
      Steak: 'Steak',
      Strawberries: 'Strawberries',
      Sugar: 'Sugar',
      SunflowerOil: 'Sunflower oil',
      SweetCorn: 'Sweet Corn',
      SweetPotato: 'Sweet Potato',
      SwissChard: 'Swiss Chard',
      Tahini: 'Tahini',
      Taro: 'Taro',
      Tarragon: 'Tarragon',
      Tea: 'Tea',
      Tofu: 'Tofu',
      Tomato: 'Tomato',
      TomatoPaste: 'Tomato Paste',
      Tortillas: 'Tortillas',
      Tumeric: 'Turmeric',
      Tuna: 'Tuna',
      Turnips: 'Turnips',
      Vanilla: 'Vanilla',
      Vegetables: 'Vegetables',
      Vinegar: 'Vinegar',
      Walnuts: 'Walnuts',
      Water: 'Water',
      Watermelon: 'Watermelon',
      Wheat: 'Wheat',
      Whey: 'Whey',
      WhiteFish: 'White Fish',
      WhiteWine: 'White Wine',
      Yogurt: 'Yogurt',
      Zucchini: 'Zucchini'
    },
    FR: {
      menuTitle: 'Menu pour vous',
      generatingMealPlan: 'Génération de votre plan de repas...',
      reGenerateMeals: 'Re-générer les repas',
      breakfast: 'Petit-déjeuner',
      lunch: 'Déjeuner',
      dinner: 'Dîner',
      flavorText: 'Profitez de vos repas!',
      mealDetails: 'Ingrédients: {ingredients}, Quantité: {quantity}g, Énergie: {totalEnergy} kcal',
      acaiBowl: 'Bol d\'Açaï',
      almondButterToast: 'Toast au beurre d\'amandes',
      appleCinnamonOatmeal: 'Flocons d\'avoine pomme cannelle',
      appleCinnamonOvernightOats: 'Flocons d\'avoine pomme cannelle pendant la nuit',
      avocadoToast: 'Toast à l\'avocat',
      baconEggBreakfastBowl: 'Bol de petit-déjeuner bacon et œuf',
      bagelWithLox: 'Bagel au saumon fumé',
      bakedEggsWithSpinach: 'Œufs au four avec épinards',
      bananaPancakes: 'Pancakes à la banane',
      berryQuinoaSalad: 'Salade de quinoa aux baies',
      berrySmoothieBowl: 'Bol de smoothie aux baies',
      blueberryMuffin: 'Muffin aux myrtilles',
      breakfastBowl: 'Bol de petit-déjeuner',
      breakfastBurrito: 'Burrito de petit-déjeuner',
      breakfastCasserole: 'Casserole de petit-déjeuner',
      breakfastCrepes: 'Crêpes de petit-déjeuner',
      breakfastEggsAndSausage: 'Œufs et saucisse de petit-déjeuner',
      breakfastEggsBenedict: 'Œufs bénédict de petit-déjeuner',
      breakfastFriedRice: 'Riz frit de petit-déjeuner',
      breakfastFruitSalad: 'Salade de fruits de petit-déjeuner',
      breakfastGranolaBars: 'Barres de granola de petit-déjeuner',
      breakfastHashBowl: 'Bol de hachis de petit-déjeuner',
      breakfastPasta: 'Pâtes de petit-déjeuner',
      breakfastPitaPocket: 'Pita farci de petit-déjeuner',
      breakfastQuiche: 'Quiche de petit-déjeuner',
      breakfastQuinoa: 'Quinoa de petit-déjeuner',
      breakfastQuinoaBowl: 'Bol de quinoa de petit-déjeuner',
      breakfastSandwich: 'Sandwich de petit-déjeuner',
      breakfastSmoothie: 'Smoothie de petit-déjeuner',
      breakfastStuffedPeppers: 'Poivrons farcis de petit-déjeuner',
      breakfastTacos: 'Tacos de petit-déjeuner',
      breakfastTofuScramble: 'Tofu brouillé de petit-déjeuner',
      buckwheatPorridge: 'Porridge de sarrasin',
      carrotCakeOatmeal: 'Flocons d\'avoine au gâteau de carottes',
      carrotZucchiniMuffins: 'Muffins carotte et courgette',
      chiaPudding: 'Pudding de chia',
      chiaSeedPudding: 'Pudding aux graines de chia',
      chocolateChiaPudding: 'Pudding de chia au chocolat',
      chocolateChipMuffins: 'Muffins aux pépites de chocolat',
      chocolateChipPancakes: 'Pancakes aux pépites de chocolat',
      chocolateProteinPancakes: 'Pancakes protéinés au chocolat',
      chocolateProteinShake: 'Shake protéiné au chocolat',
      cinnamonRolls: 'Roulés à la cannelle',
      coconutChiaPudding: 'Pudding de chia à la noix de coco',
      coconutRicePudding: 'Riz au lait de coco',
      cornmealMush: 'Polenta de maïs',
      cottageCheeseWithFruit: 'Fromage cottage avec fruits',
      eggAndSpinachWrap: 'Wrap œuf et épinards',
      eggBenedict: 'Œufs bénédict',
      eggsFlorentine: 'Œufs florentine',
      eggWhiteFrittata: 'Frittata aux blancs d\'œufs',
      eggWhiteOmelette: 'Omelette aux blancs d\'œufs',
      frenchToast: 'Pain perdu',
      frittata: 'Frittata',
      fruitAndNutBars: 'Barres aux fruits et aux noix',
      fruitAndNutGranola: 'Granola aux fruits et aux noix',
      fruitSalad: 'Salade de fruits',
      fruitSmoothie: 'Smoothie aux fruits',
      granola: 'Granola',
      granolaEnergyBites: 'Bouchées énergétiques au granola',
      greekYogurtParfait: 'Parfait de yaourt grec',
      hamEggs: 'Jambon et œufs',
      mangoChiaParfait: 'Parfait mangue et chia',
      maplePecanOatmeal: 'Flocons d\'avoine érable et pacanes',
      mixedBerryParfait: 'Parfait aux baies mélangées',
      muesli: 'Muesli',
      mushroomQuinoaBreakfast: 'Petit-déjeuner quinoa et champignons',
      nutButterBananaToast: 'Toast banane et beurre de noix',
      nutellaStuffedPancakes: 'Pancakes farcis au Nutella',
      nuttyGranolaBars: 'Barres de granola aux noix',
      oatmeal: 'Flocons d\'avoine',
      oatmealBreakfastCookies: 'Biscuits de petit-déjeuner aux flocons d\'avoine',
      oatmealCookies: 'Biscuits aux flocons d\'avoine',
      oatmealFruitBowl: 'Bol de flocons d\'avoine aux fruits',
      oatmealFruitCups: 'Coupes de flocons d\'avoine aux fruits',
      orangeAlmondGranola: 'Granola orange et amandes',
      overnightOats: 'Flocons d\'avoine pendant la nuit',
      pancakes: 'Pancakes',
      peanutButterBananaSmoothie: 'Smoothie banane et beurre de cacahuète',
      peanutButterSmoothie: 'Smoothie au beurre de cacahuète',
      poachedEggs: 'Œufs pochés',
      proteinPancakes: 'Pancakes protéinés',
      pumpkinPancakes: 'Pancakes à la citrouille',
      quiche: 'Quiche',
      quinoaBreakfastBowl: 'Bol de petit-déjeuner au quinoa',
      ricePudding: 'Riz au lait',
      ricottaToastWithBerries: 'Toast ricotta et baies',
      sausageBreakfastBowl: 'Bol de petit-déjeuner à la saucisse',
      savoryBreakfastBowl: 'Bol de petit-déjeuner salé',
      savoryBreakfastPancakes: 'Pancakes salés',
      savoryScones: 'Scones salés',
      scrambledEggs: 'Œufs brouillés',
      shakshuka: 'Shakshuka',
      smoothie: 'Smoothie',
      smoothieBowl: 'Bol de smoothie',
      spicedAppleCiderDonuts: 'Beignets au cidre de pomme épicé',
      spicyAvocadoEggToast: 'Toast épicé avocat et œuf',
      spicyTofuScramble: 'Tofu brouillé épicé',
      spinachAndFetaWrap: 'Wrap épinards et feta',
      spinachFetaEggWrap: 'Wrap œufs, épinards et feta',
      spinachFetaQuiche: 'Quiche épinards et feta',
      spinachSmoothie: 'Smoothie aux épinards',
      strawberryBananaSmoothie: 'Smoothie fraise et banane',
      sweetPotatoFrittata: 'Frittata aux patates douces',
      sweetPotatoHash: 'Hachis de patates douces',
      sweetPotatoPancakes: 'Pancakes aux patates douces',
      tropicalFruitSalad: 'Salade de fruits tropicaux',
      tropicalSmoothie: 'Smoothie tropical',
      veggieBreakfastWrap: 'Wrap végétarien de petit-déjeuner',
      veggieOmelette: 'Omelette végétarienne',
      wholeGrainToastWithAvocado: 'Toast de grains entiers à l\'avocat',
      wholeWheatBagel: 'Bagel de blé entier',
      yogurtParfait: 'Parfait au yaourt',
      zucchiniBread: 'Pain aux courgettes',
      zucchiniFritters: 'Beignets de courgettes',
      almondMilkUnsweetened: 'Lait d\'amande (Non sucré)',
      avocadoSmoothie: 'Smoothie à l\'avocat',
      blackCoffee: 'Café noir',
      blueberryChiaSmoothie: 'Smoothie aux myrtilles et chia',
      carrotJuice: 'Jus de carotte',
      chiaSeedWater: 'Eau de graines de chia',
      coconutWater: 'Eau de coco',
      gingerTea: 'Thé au gingembre',
      greenSmoothie: 'Smoothie vert',
      honeyLemonWater: 'Eau citron-miel',
      mangoSmoothie: 'Smoothie à la mangue',
      matchaLatte: 'Matcha latte',
      oatMilkUnsweetened: 'Lait d\'avoine (Non sucré)',
      orangeJuice: 'Jus d\'orange',
      peppermintTea: 'Thé à la menthe poivrée',
      pomegranateJuice: 'Jus de grenade',
      soyMilk: 'Lait de soja',
      strawberrySmoothie: 'Smoothie à la fraise',
      turmericLatte: 'Lait doré au curcuma',
      watermelonJuice: 'Jus de pastèque',
      almondMilkYogurt: 'Yaourt au lait d’amande',
      asiagoCheese: 'Fromage Asiago',
      blueberryYogurt: 'Yaourt aux myrtilles',
      blueCheese: 'Fromage bleu',
      brieCheese: 'Fromage Brie',
      burrataCheese: 'Fromage Burrata',
      cabraAlVinoCheese: 'Fromage Cabra al Vino',
      camembertCheese: 'Fromage Camembert',
      cantalCheese: 'Fromage Cantal',
      casuMarzuCheese: 'Fromage Casu Marzu',
      chabichouCheese: 'Fromage Chabichou',
      cheddarCheese: 'Fromage Cheddar',
      cheshireCheese: 'Fromage Cheshire',
      chevreCheese: 'Fromage Chèvre',
      chocolateYogurt: 'Yaourt au chocolat',
      coconutMilkYogurt: 'Yaourt au lait de coco',
      comteCheese: 'Fromage Comté',
      cotijaCheese: 'Fromage Cotija',
      cottegeCheese: 'Fromage Cottage',
      crottinCheese: 'Fromage Crottin',
      emmentalCheese: 'Fromage Emmental',
      fetaCheese: 'Fromage Feta',
      gorgonzolaCheese: 'Fromage Gorgonzola',
      goudaCheese: 'Fromage Gouda',
      gruyereCheese: 'Fromage Gruyère',
      halloumiCheese: 'Fromage Halloumi',
      havartiCheese: 'Fromage Havarti',
      honeyGreekYogurt: 'Yaourt grec au miel',
      kefir: 'Kéfir',
      langresCheese: 'Fromage Langres',
      leerdammerCheese: 'Fromage Leerdammer',
      limburgerCheese: 'Fromage Limburger',
      livarotCheese: 'Fromage Livarot',
      lowFatYogurt: 'Yaourt allégé',
      manchegoCheese: 'Fromage Manchego',
      mangoYogurt: 'Yaourt à la mangue',
      mimoletteCheese: 'Fromage Mimolette',
      mozzarellaCheese: 'Fromage Mozzarella',
      muensterCheese: 'Fromage Munster',
      neufchâtelCheese: 'Fromage Neufchâtel',
      nevatCheese: 'Fromage Nevat',
      parmesanCheese: 'Fromage Parmesan',
      peachYogurt: 'Yaourt à la pêche',
      pecorinoCheese: 'Fromage Pecorino',
      plainGreekYogurt: 'Yaourt grec nature',
      quarkCheese: 'Fromage Quark',
      quesoFrescoCheese: 'Fromage Queso Fresco',
      raspberryYogurt: 'Yaourt à la framboise',
      ricottaCheese: 'Fromage Ricotta',
      roquefortCheese: 'Fromage Roquefort',
      saintNectaireCheese: 'Fromage Saint-Nectaire',
      smokedGouda: 'Gouda fumé',
      sourCreamCheese: 'Fromage à la crème sure',
      soyYogurt: 'Yaourt de soja',
      stinkingBishopCheese: 'Fromage Stinking Bishop',
      strawberryYogurt: 'Yaourt à la fraise',
      taleggioCheese: 'Fromage Taleggio',
      tommeDeSavoieCheese: 'Fromage Tomme de Savoie',
      vacherinCheese: 'Fromage Vacherin',
      valdeonCheese: 'Fromage Valdeón',
      vanillaYogurt: 'Yaourt à la vanille',
      wholeMilkYogurt: 'Yaourt au lait entier',
      yorkshireBlueCheese: 'Fromage Yorkshire Blue',
      almondCake: 'Gâteau aux amandes',
      almondJoyBars: 'Barres Joy Amande',
      appleCrisp: 'Croustillant aux pommes',
      appleCrumble: 'Crumble aux pommes',
      appleOatmealPancakes: 'Pancakes avoine-pomme',
      applePie: 'Tarte aux pommes',
      baklava: 'Baklava',
      bananaBread: 'Pain à la banane',
      bananaNutBread: 'Pain aux bananes et noix',
      bananaPudding: 'Pudding à la banane',
      bananaSplit: 'Banana Split',
      blueberryCheesecake: 'Cheesecake aux myrtilles',
      blueberryPie: 'Tarte aux myrtilles',
      brownies: 'Brownies',
      caramelAppleDumpCake: 'Gâteau renversé aux pommes et caramel',
      caramelFlan: 'Flan au caramel',
      caramelPopcorn: 'Popcorn au caramel',
      carrotCake: 'Gâteau aux carottes',
      cheesecake: 'Cheesecake',
      cherryAlmondGranola: 'Granola cerise et amande',
      cherryClafoutis: 'Clafoutis aux cerises',
      chocolateBavarianCream: 'Crème bavaroise au chocolat',
      chocolateBrownies: 'Brownies au chocolat',
      chocolateCake: 'Gâteau au chocolat',
      chocolateChipCookies: 'Cookies aux pépites de chocolat',
      chocolateCoconutBalls: 'Boules chocolat-coco',
      chocolateCoconutPie: 'Tarte chocolat-noix de coco',
      chocolateCoveredStrawberries: 'Fraises enrobées de chocolat',
      chocolateDippedBananas: 'Bananes trempées au chocolat',
      chocolateEclair: 'Éclair au chocolat',
      chocolateFondue: 'Fondue au chocolat',
      chocolateFudgeCake: 'Gâteau fondant au chocolat',
      chocolateMilkshake: 'Milkshake au chocolat',
      chocolateMintBrownies: 'Brownies chocolat-menthe',
      chocolateMousse: 'Mousse au chocolat',
      chocolatePavlova: 'Pavlova au chocolat',
      chocolatePeanutButterBars: 'Barres chocolat-beurre de cacahuète',
      chocolatePecanPie: 'Tarte aux pacanes et chocolat',
      chocolatePudding: 'Pudding au chocolat',
      chocolateRaspberryTrifle: 'Trifle chocolat-framboise',
      chocolateSouffle: 'Soufflé au chocolat',
      chocolateTart: 'Tarte au chocolat',
      churros: 'Churros',
      coconutCreamPie: 'Tarte à la crème de coco',
      coconutMacaroons: 'Macarons à la noix de coco',
      custard: 'Crème anglaise',
      eclair: 'Éclair',
      frozenYogurt: 'Yaourt glacé',
      fruitTart: 'Tarte aux fruits',
      fudgeBrownies: 'Brownies fondants',
      gelato: 'Gelato',
      gingerbread: 'Pain d’épices',
      gingerbreadCookies: 'Biscuits pain d’épices',
      honeycombToffee: 'Caramel au nid d’abeille',
      keyLimePie: 'Tarte au citron vert',
      lemonMeringuePie: 'Tarte au citron meringuée',
      macaron: 'Macaron',
      matchaGreenTeaCake: 'Gâteau au thé vert matcha',
      matchaPancakes: 'Pancakes au matcha',
      moltenChocolateCake: 'Moelleux au chocolat',
      oatmealBananaCookies: 'Cookies avoine-banane',
      oatmealRaisinCookies: 'Cookies avoine-raisins secs',
      orangeSorbet: 'Sorbet à l’orange',
      orangeUpsideDownCake: 'Gâteau renversé à l’orange',
      pannaCotta: 'Panna Cotta',
      pannaCottaCoconut: 'Panna Cotta coco',
      pannaCottaVanilla: 'Panna Cotta vanille',
      pavlova: 'Pavlova',
      peachCobbler: 'Cobbler aux pêches',
      peachMelba: 'Pêche Melba',
      pecanPie: 'Tarte aux pacanes',
      profiteroles: 'Profiteroles',
      pumpkinPie: 'Tarte à la citrouille',
      pumpkinSpiceLatte: 'Latte à la citrouille épicée',
      pumpkinSpicePancakes: 'Pancakes épicés à la citrouille',
      quinoaFruitBowl: 'Bol de fruits au quinoa',
      raspberryMousse: 'Mousse à la framboise',
      raspberrySorbet: 'Sorbet à la framboise',
      redVelvetCake: 'Gâteau Red Velvet',
      redWinePoachedPears: 'Poires pochées au vin rouge',
      snickerdoodleCookies: 'Cookies snickerdoodle',
      stickyRiceMango: 'Riz gluant à la mangue',
      strawberryCheesecake: 'Cheesecake aux fraises',
      strawberryShortcake: 'Shortcake aux fraises',
      sweetPotatoPie: 'Tarte aux patates douces',
      tiramisu: 'Tiramisu',
      tiramisuCupcakes: 'Cupcakes Tiramisu',
      vanillaBeanIceCream: 'Glace à la vanille',
      vanillaCupcake: 'Cupcake à la vanille',
      vanillaIceCream: 'Glace à la vanille',
      vanillaPudding: 'Pudding à la vanille',
      whiteChocolateRaspberryCheesecake: 'Cheesecake chocolat blanc-framboise',
      baconCheeseburger: 'Bacon Cheeseburger',
      bakedPotato: 'Pomme de terre au four',
      bakedZiti: 'Ziti au four',
      bangersAndMash: 'Saucisses purée',
      barbecueChicken: 'Poulet barbecue',
      beefAndBroccoli: 'Bœuf et brocoli',
      beefBourgignon: 'Bœuf Bourguignon',
      beefRagu: 'Ragoût de bœuf',
      beefStroganoff: 'Bœuf Stroganoff',
      beefTacos: 'Tacos au bœuf',
      blackBeanTacos: 'Tacos aux haricots noirs',
      bltSandwich: 'Sandwich BLT',
      bolognesePasta: 'Pâtes à la bolognaise',
      butterChicken: 'Poulet au beurre',
      butternutSquashRisotto: 'Risotto à la courge butternut',
      cabbageRolls: 'Roulés au chou',
      carrotGingerSoup: 'Soupe carotte et gingembre',
      chanaMasala: 'Chana Masala',
      chickenAdobo: 'Poulet Adobo',
      chickenAlfredo: 'Poulet Alfredo',
      chickenAndRice: 'Poulet et riz',
      chickenCaesarSalad: 'Salade César au poulet',
      chickenCurry: 'Curry de poulet',
      chickenFajitas: 'Fajitas au poulet',
      chickenKorma: 'Poulet Korma',
      chickenNoodleSoup: 'Soupe de poulet aux nouilles',
      chickenParmesan: 'Poulet Parmesan',
      chickenPotPie: 'Tourte au poulet',
      chickenSchnitzel: 'Escalope de poulet',
      chickenSouvlaki: 'Souvlaki de poulet',
      chickenTikkaMasala: 'Poulet Tikka Masala',
      chiliConCarne: 'Chili con carne',
      clamChowder: 'Chaudrée de palourdes',
      coconutRice: 'Riz à la noix de coco',
      coqAuVin: 'Coq au vin',
      cornChowder: 'Chaudrée de maïs',
      creamyMushroomRisotto: 'Risotto crémeux aux champignons',
      creamySpinachPasta: 'Pâtes crémeuses aux épinards',
      crispyDuck: 'Canard croustillant',
      curryChicken: 'Poulet au curry',
      curryTofu: 'Tofu au curry',
      eggFriedRice: 'Riz frit aux œufs',
      eggplantParmesan: 'Aubergine Parmesan',
      eggSalad: 'Salade aux œufs',
      falafelBowl: 'Bol de falafels',
      falafelWrap: 'Wrap aux falafels',
      fishAndChips: 'Poisson et frites',
      fishTacos: 'Tacos au poisson',
      friedRice: 'Riz frit',
      garlicButterPasta: 'Pâtes au beurre et à l’ail',
      garlicPasta: 'Pâtes à l’ail',
      gnocchi: 'Gnocchi',
      gnocchiAlPesto: 'Gnocchi au pesto',
      goulash: 'Goulash',
      grilledCheeseSandwich: 'Croque-monsieur',
      grilledEggplantParmesan: 'Aubergine Parmesan grillée',
      grilledLemonChicken: 'Poulet grillé au citron',
      grilledVegetableWrap: 'Wrap aux légumes grillés',
      grilledVeggiePasta: 'Pâtes aux légumes grillés',
      gyros: 'Gyros',
      jambalaya: 'Jambalaya',
      jerkChicken: 'Poulet jerk',
      kebab: 'Kebab',
      kimchiFriedRice: 'Riz frit au kimchi',
      lambChops: 'Côtelettes d’agneau',
      lemonButterShrimp: 'Crevettes au beurre et citron',
      lemonGarlicTilapia: 'Tilapia citron et ail',
      lobsterRoll: 'Rouleau de homard',
      macaroniAndCheese: 'Macaroni au fromage',
      mediterraneanQuinoaBowl: 'Bol de quinoa méditerranéen',
      misoRamen: 'Ramen au miso',
      mixedVegetableStirFry: 'Sauté de légumes',
      moussaka: 'Moussaka',
      mushroomRisotto: 'Risotto aux champignons',
      padKrapowMoo: 'Pad Krapow Moo',
      padThai: 'Pad Thaï',
      paella: 'Paella',
      pestoPasta: 'Pâtes au pesto',
      phillyCheesesteak: 'Cheesesteak de Philadelphie',
      pokeBowl: 'Bol de poke',
      porkChop: 'Côtelette de porc',
      pulledPorkSandwich: 'Sandwich au porc effiloché',
      quesadilla: 'Quesadilla',
      quicheLorraine: 'Quiche Lorraine',
      quinoaStuffedEggplant: 'Aubergine farcie au quinoa',
      ratatouille: 'Ratatouille',
      risotto: 'Risotto',
      risottoMushrooms: 'Risotto aux champignons',
      roastedVegetableQuinoa: 'Quinoa aux légumes rôtis',
      salmonFillet: 'Filet de saumon',
      salmonPasta: 'Pâtes au saumon',
      sausageAndMash: 'Saucisses purée',
      seafoodPaella: 'Paella aux fruits de mer',
      seafoodRisotto: 'Risotto aux fruits de mer',
      shepherdsPie: 'Hachis Parmentier',
      shrimpFriedRice: 'Riz frit aux crevettes',
      shrimpScampi: 'Scampi aux crevettes',
      spaghettiCarbonara: 'Spaghetti à la carbonara',
      spicyShrimpTacos: 'Tacos aux crevettes épicées',
      spicyTofuStirFry: 'Sauté de tofu épicé',
      spinachLasagna: 'Lasagne aux épinards',
      stuffedBellPeppers: 'Poivrons farcis',
      sushiRoll: 'Rouleau de sushi',
      sweetPotatoCasserole: 'Gratin de patates douces',
      sweetPotatoCurry: 'Curry de patates douces',
      teriyakiChicken: 'Poulet teriyaki',
      teriyakiSalmon: 'Saumon teriyaki',
      teriyakiShrimp: 'Crevettes teriyaki',
      teriyakiTofu: 'Tofu teriyaki',
      turkeyChili: 'Chili de dinde',
      turkeyMeatballs: 'Boulettes de dinde',
      veganChili: 'Chili végétalien',
      vegetableStirFry: 'Sauté de légumes',
      veggieBurger: 'Burger végétarien',
      veggieLasagna: 'Lasagne végétarienne',
      veggieStirFry: 'Sauté de légumes',
      zucchiniLasagna: 'Lasagne de courgettes',
      zucchiniNoodles: 'Nouilles de courgettes',
      antipastoPlatter: 'Plateau d\'Antipasto',
      avocadoEggSalad: 'Salade d\'œuf et d\'avocat',
      avocadoSpringRolls: 'Rouleaux de printemps à l\'avocat',
      baconCheddarPotatoSkins: 'Pommes de terre bacon cheddar',
      baconWrappedAsparagus: 'Asperges enrobées de bacon',
      baconWrappedDates: 'Dattes enrobées de bacon',
      beetHummus: 'Houmous de betterave',
      beetrootSalad: 'Salade de betterave',
      beetSalad: 'Salade de betterave',
      bruschetta: 'Bruschetta',
      bruschettaSalad: 'Salade de bruschetta',
      butternutSquashSoup: 'Soupe de courge butternut',
      caponata: 'Caponata',
      capreseSalad: 'Salade caprese',
      carrotHummus: 'Houmous de carotte',
      carrotSticksWithDip: 'Bâtonnets de carottes avec sauce',
      cheeseAndCrackers: 'Fromage et crackers',
      cheesePlatter: 'Plateau de fromages',
      cheeseQuesadilla: 'Quesadilla au fromage',
      cheeseStuffedPeppers: 'Poivrons farcis au fromage',
      chickenQuesadilla: 'Quesadilla au poulet',
      chickenSatay: 'Satay de poulet',
      chickenWings: 'Ailes de poulet',
      chickpeaSalad: 'Salade de pois chiches',
      chiliCheeseFries: 'Frites au chili et fromage',
      coconutShrimp: 'Crevettes à la noix de coco',
      cornFritters: 'Beignets de maïs',
      crabCakes: 'Crab cakes',
      crabPuffs: 'Feuilletés au crabe',
      crabRangoon: 'Crabe Rangoon',
      crispyTofuBites: 'Bouchées de tofu croustillant',
      cucumberAndHummus: 'Concombre et houmous',
      deviledEggs: 'Œufs mimosa',
      eggplantCaviar: 'Caviar d\'aubergine',
      falafel: 'Falafel',
      fruitSkewers: 'Brochettes de fruits',
      garlicBread: 'Pain à l\'ail',
      garlicParmesanBread: 'Pain à l\'ail et au parmesan',
      garlicParmesanMushrooms: 'Champignons au parmesan et à l\'ail',
      gazpacho: 'Gaspacho',
      greekSalad: 'Salade grecque',
      grilledVegetableSkewers: 'Brochettes de légumes grillés',
      lentilSalad: 'Salade de lentilles',
      lentilSoup: 'Soupe de lentilles',
      loadedNachos: 'Nachos garnis',
      mangoSalsa: 'Salsa à la mangue',
      marinatedOlives: 'Olives marinées',
      meatballs: 'Boulettes de viande',
      miniPizzas: 'Mini pizzas',
      miniQuiches: 'Mini quiches',
      onionSoup: 'Soupe à l\'oignon',
      peaSoup: 'Soupe de pois',
      potatoCroquettes: 'Croquettes de pommes de terre',
      potatoSkins: 'Pommes de terre farcies',
      prosciuttoMelon: 'Prosciutto et melon',
      pumpkinSoup: 'Soupe de potiron',
      quinoaSalad: 'Salade de quinoa',
      quinoaTabbouleh: 'Taboulé de quinoa',
      roastedGarlicBread: 'Pain à l\'ail rôti',
      roastedRedPepperHummus: 'Houmous aux poivrons rouges rôtis',
      salmonSushi: 'Sushi au saumon',
      savoryCheeseScones: 'Scones au fromage',
      shrimpCeviche: 'Ceviche de crevettes',
      shrimpCocktail: 'Cocktail de crevettes',
      shrimpSpringRolls: 'Rouleaux de printemps aux crevettes',
      shrimpTacos: 'Tacos aux crevettes',
      smokedSalmonCanapés: 'Canapés au saumon fumé',
      spicedSweetPotatoWedges: 'Quartiers de patates douces épicées',
      spicyChickenWings: 'Ailes de poulet épicées',
      spicyHummus: 'Houmous épicé',
      spicyLentilSoup: 'Soupe de lentilles épicée',
      spinachArtichokeDip: 'Trempette épinards et artichauts',
      spinachFetaPuffs: 'Feuilletés épinards et feta',
      springRolls: 'Rouleaux de printemps',
      stuffedMushrooms: 'Champignons farcis',
      stuffedPeppers: 'Poivrons farcis',
      sweetCornFritters: 'Beignets de maïs sucré',
      sweetPotatoFries: 'Frites de patates douces',
      tempuraVegetables: 'Tempura de légumes',
      tomatoBasilSoup: 'Soupe tomate basilic',
      tunaSalad: 'Salade de thon',
      tunaTartare: 'Tartare de thon',
      veganStuffedMushrooms: 'Champignons farcis végan',
      vegetableSamosas: 'Samosas de légumes',
      vegetableSpringRolls: 'Rouleaux de printemps aux légumes',
      vegetableSushi: 'Sushi de légumes',
      vegetableTempura: 'Tempura de légumes',
      watermelonFetaSalad: 'Salade de pastèque et feta',
      wildRiceSalad: 'Salade de riz sauvage',
      asparagus: 'Asperge',
      bellPepper: 'Poivron',
      bitterMelon: 'Melon amer',
      broccoli: 'Brocoli',
      brusselsSprouts: 'Choux de Bruxelles',
      butternutSquash: 'Courge butternut',
      carrot: 'Carotte',
      cauliflower: 'Chou-fleur',
      cucumber: 'Concombre',
      daikon: 'Daikon',
      eggplant: 'Aubergine',
      fennel: 'Fenouil',
      kale: 'Chou frisé',
      lettuce: 'Laitue',
      mustardGreens: 'Feuilles de moutarde',
      parsnip: 'Panais',
      radish: 'Radis',
      seaweed: 'Algue',
      spinach: 'Épinard',
      sweetPotato: 'Patate douce',
      swissChard: 'Bette à carde',
      tomato: 'Tomate',
      turnip: 'Navet',
      waterSpinach: 'Épinard d’eau',
      zucchini: 'Courgette',
      apple: 'Pomme',
      banana: 'Banane',
      blueberry: 'Myrtille',
      carambola: 'Carambole',
      cherries: 'Cerises',
      cloudberry: 'Mûre des marais',
      custardApple: 'Pomme cannelle',
      dragonFruit: 'Fruit du dragon',
      feijoa: 'Feijoa',
      fig: 'Figue',
      grapefruit: 'Pamplemousse',
      guava: 'Goyave',
      jackfruit: 'Jacquier',
      kiwi: 'Kiwi',
      kumquat: 'Kumquat',
      lychee: 'Litchi',
      mango: 'Mangue',
      mulberry: 'Mûrier',
      orange: 'Orange',
      papaya: 'Papaye',
      passionFruit: 'Fruit de la passion',
      pear: 'Poire',
      persimmon: 'Kaki',
      pineapple: 'Ananas',
      pomegranate: 'Grenade',
      rambutan: 'Ramboutan',
      raspberries: 'Framboises',
      sapodilla: 'Sapote',
      starfruit: 'Carambole',
      strawberry: 'Fraise',
      watermelon: 'Pastèque',
      Acai: 'Purée d\'acai',
      Acid: 'Acide',
      Alcohol: 'Alcool',
      Almond: 'Lait d\'amande',
      AlmondMilk: 'Lait d\'amande',
      Apple: 'Pomme',
      ArborioRice: 'Riz Arborio',
      Artichokes: 'Artichauts',
      Asparagus: 'Asperges',
      AssortedCheeses: 'Fromages assortis',
      AssortedVegetables: 'Légumes assortis',
      Avocado: 'Avocat',
      AvocadoOil: 'Huile d\'avocat',
      Bacon: 'Bacon',
      Bagel: 'Bagel',
      BakingPowder: 'Poudre à lever',
      BacterialCultures: 'Cultures bactériennes',
      Banana: 'Banane',
      BarbecueSauce: 'Sauce barbecue',
      Barley: 'Orge',
      Basil: 'Basilic',
      Batter: 'Pâte',
      BayLeaf: 'Feuille de laurier',
      BeanSprouts: 'Pousses de haricot',
      Beans: 'Haricots',
      Beef: 'Boeuf',
      BeefBroth: 'Bouillon de boeuf',
      Beets: 'Betteraves',
      BellPeppers: 'Poivrons',
      Berries: 'Baies',
      BitterMelon: 'Melon amer',
      BlackBeans: 'Haricots noirs',
      BlackPepper: 'Poivre noir',
      Blueberries: 'Myrtilles',
      Bread: 'Pain',
      Breadcrumbs: 'Chapelure',
      Breading: 'Enrobage',
      Broccoli: 'Brocoli',
      Broth: 'Bouillon',
      BrusselsSprouts: 'Choux de Bruxelles',
      Buckwheat: 'Sarrasin',
      Bun: 'Petit pain',
      Butter: 'Beurre',
      Buttermilk: 'Lait caillé',
      ButternutSquash: 'Courge butternut',
      CaesarDressing: 'Vinaigrette César',
      Cabbage: 'Chou',
      Capers: 'Câpres',
      Carambola: 'Carambole',
      Carrot: 'Carotte',
      Cauliflower: 'Chou-fleur',
      Celery: 'Céleri',
      Cereal: 'Céréales',
      CheddarCheese: 'Fromage cheddar',
      Cheese: 'Fromage',
      Cherries: 'Cerises',
      Chickpeas: 'Pois chiches',
      Chicken: 'Poulet',
      Chili: 'Piment',
      ChiliPowder: 'Poudre de piment',
      Chocolate: 'Chocolat',
      Chia: 'Graines de chia',
      Cider: 'Cidre',
      Cilantro: 'Coriandre',
      Cinnamon: 'Cannelle',
      Clams: 'Palourdes',
      Cloudberry: 'Mûre des marais',
      Cocoa: 'Cacao',
      Coconut: 'Noix de coco',
      CoconutMilk: 'Lait de coco',
      CoconutOil: 'Huile de coco',
      CocktailSauce: 'Sauce cocktail',
      Coffee: 'Café',
      Coleslaw: 'Salade de chou',
      Corn: 'Maïs',
      Cornstarch: 'Fécule de maïs',
      Couscous: 'Couscous',
      CrabMeat: 'Viande de crabe',
      Crackers: 'Craquelins',
      Cream: 'Crème',
      CreamCheese: 'Fromage à la crème',
      Croutons: 'Croûtons',
      Cucumber: 'Concombre',
      Cumin: 'Cumin',
      Curry: 'Curry',
      CustardApple: 'Pomme-custard',
      DriedFruits: 'Fruits secs',
      Daikon: 'Daikon',
      DarkChocolate: 'Chocolat noir',
      Dates: 'Dattes',
      DragonFruit: 'Fruit du dragon',
      Dressings: 'Vinaigrettes',
      Duck: 'Canard',
      Egg: 'Œuf',
      Eggplant: 'Aubergine',
      Feijoa: 'Feijoa',
      Fennel: 'Fenouil',
      Fig: 'Figue',
      Fish: 'Poisson',
      Flour: 'Farine',
      Fries: 'Frites',
      Fruits: 'Fruits',
      Garlic: 'Ail',
      Gelatin: 'Gélatine',
      Ginger: 'Gingembre',
      Gnocchi: 'Gnocchi',
      GoatsMilk: 'Lait de chèvre',
      Grapefruit: 'Pamplemousse',
      Grapes: 'Raisins',
      Granola: 'Granola',
      Gravy: 'Sauce',
      GreekYogurt: 'Yaourt grec',
      GreenOnions: 'Oignons verts',
      GrilledVegetables: 'Légumes grillés',
      GroundMeat: 'Viande hachée',
      Guava: 'Goyave',
      Ham: 'Jambon',
      Herbs: 'Herbes',
      HoagieRoll: 'Pain hoagie',
      Hollandaise: 'Sauce hollandaise',
      Honey: 'Miel',
      HotDogBun: 'Pain à hot-dog',
      HotSauce: 'Sauce piquante',
      Hummus: 'Houmous',
      IceCream: 'Crème glacée',
      Insect: 'Larves d\'insectes vivantes',
      Jackfruit: 'Jacquier',
      Jalapeños: 'Jalapeños',
      JerkMarinade: 'Marinade jerk',
      Juices: 'Jus',
      Kale: 'Chou frisé',
      Kimchi: 'Kimchi',
      Kiwi: 'Kiwi',
      Kumquat: 'Kumquat',
      Lamb: 'Agneau',
      Leeks: 'Poireaux',
      Lemon: 'Citron',
      Lettuce: 'Laitue',
      Lentils: 'Lentilles',
      LimeJuice: 'Jus de citron vert',
      Lobster: 'Homard',
      Lychee: 'Litchi',
      Macaroni: 'Macaroni',
      Mango: 'Mangue',
      MapleSyrup: 'Sirop d\'érable',
      Maplesyrup: 'Sirop d\'érable',
      MarinaraSauce: 'Sauce marinara',
      MarinatedVegetables: 'Légumes marinés',
      Marshmallows: 'Guimauves',
      Mayonnaise: 'Mayonnaise',
      Matcha: 'Poudre de matcha',
      Melon: 'Melon',
      Milk: 'Lait',
      Mint: 'Menthe',
      Miso: 'Miso',
      MixedFruits: 'Fruits mélangés',
      MixedVegetables: 'Légumes mélangés',
      Mixedberries: 'Baies mélangées',
      Mixedfruit: 'Fruits mélangés',
      Mixedfruits: 'Fruits mélangés (pommes, baies, oranges)',
      Mozzarella: 'Mozzarella',
      Muffin: 'Muffin anglais',
      Muffins: 'Muffin',
      Mulberry: 'Mûre',
      Mushrooms: 'Champignons',
      Mussels: 'Moules',
      Mustard: 'Moutarde',
      Noodles: 'Nouilles',
      Nutmeg: 'Muscade',
      Nuts: 'Noix',
      Oatmeal: 'Flocons d\'avoine',
      Oats: 'Avoine',
      Oil: 'Huile',
      Olives: 'Olives',
      Onions: 'Oignon',
      Oranges: 'Oranges',
      Oregano: 'Origan',
      Oysters: 'Huîtres',
      Pancakes: 'Crêpes',
      Papaya: 'Papaye',
      Paprika: 'Paprika',
      Parmesan: 'Parmesan',
      Parsley: 'Persil',
      Parsnips: 'Panais',
      PassionFruit: 'Fruit de la passion',
      Pasta: 'Pâtes',
      PastaSauce: 'Sauce pour pâtes',
      Pastrami: 'Pastrami',
      Peaches: 'Pêches',
      Peanut: 'Cacahuète',
      PeanutButter: 'Beurre de cacahuète',
      Pear: 'Poire',
      Pecans: 'Pécan',
      Peppers: 'Poivrons',
      Pepperoni: 'Pepperoni',
      Pickles: 'Cornichons',
      Pineapple: 'Ananas',
      Pita: 'Pita',
      PizzaDough: 'Pâte à pizza',
      Plantain: 'Plante banane',
      Plums: 'Prunes',
      Pomegranate: 'Grenade',
      Popcorn: 'Pop-corn',
      Pork: 'Porc',
      Prawns: 'Crevettes',
      Pretzels: 'Bretzels',
      PricklyPear: 'Poire épineuse',
      Prosciutto: 'Prosciutto',
      Prunes: 'Pruneaux',
      Pudding: 'Pouding',
      Pumpkin: 'Citrouille',
      PumpkinSeeds: 'Graines de citrouille',
      QuailEggs: 'Œufs de caille',
      Quinoa: 'Quinoa',
      Radicchio: 'Radicchio',
      Radishes: 'Radis',
      Raisins: 'Raisins',
      Raspberries: 'Framboises',
      Rice: 'Riz',
      RiceNoodles: 'Nouilles de riz',
      Ricotta: 'Ricotta',
      Roll: 'Roulé',
      Rosemary: 'Romarin',
      RyeBread: 'Pain de seigle',
      Salad: 'Salade',
      Salt: 'Sel',
      Salsa: 'Salsa',
      Sapodilla: 'Sapodille',
      Sausage: 'Saucisse',
      Scallops: 'Saint-Jacques',
      Seaweed: 'Algues',
      Sesame: 'Graines de sésame',
      Shallots: 'Échalotes',
      Shellfish: 'Fruits de mer',
      Shrimp: 'Crevettes',
      Sorrel: 'Rorippa',
      SoySauce: 'Sauce soja',
      Soybeans: 'Fèves de soja',
      Soymilk: 'Lait de soja',
      Spaghetti: 'Spaghetti',
      Spinach: 'Épinards',
      Squid: 'Calmar',
      SquidInk: 'Encre de seiche',
      Starfruit: 'Carambole',
      Steak: 'Steak',
      Strawberries: 'Fraises',
      Sugar: 'Sucre',
      SunflowerOil: 'Huile de tournesol',
      SweetCorn: 'Maïs doux',
      SweetPotato: 'Patate douce',
      SwissChard: 'Bette',
      Tahini: 'Tahini',
      Taro: 'Taro',
      Tarragon: 'Estragon',
      Tea: 'Thé',
      Tofu: 'Tofu',
      Tomato: 'Tomate',
      TomatoPaste: 'Pâte de tomate',
      Tortillas: 'Tortillas',
      Tumeric: 'Curcuma',
      Tuna: 'Thon',
      Turnips: 'Navets',
      Vanilla: 'Vanille',
      Vegetables: 'Légumes',
      Vinegar: 'Vinaigre',
      Walnuts: 'Noix',
      Water: 'Eau',
      Watermelon: 'Pastèque',
      Wheat: 'Blé',
      Whey: 'Petits suisses',
      WhiteFish: 'Poisson blanc',
      WhiteWine: 'Vin blanc',
      Yogurt: 'Yaourt',
      Zucchini: 'Courgette'
    }
  };

const GenerateMealsPage = ({ language }) => {
  const location = useLocation();
  const { energy, protein, fats, carbs } = location.state; // Data passed from EnergyResultPage

  const [mealPlan, setMealPlan] = useState(null);
  const [flavorText, setFlavorText] = useState('');
  
  useEffect(() => {
    generateMealPlan();
  }, [energy, protein, fats, carbs]);

  const generateMealPlan = () => {
    // Select meals for breakfast, lunch, and dinner
    const breakfast = generateMealForMealType('breakfast', energy * 0.25); // 25% of total energy for breakfast
    const lunch = generateMealForMealType('lunch', energy * 0.35); // 35% for lunch
    const dinner = generateMealForMealType('dinner', energy * 0.4); // 40% for dinner

    // Combine all meals
    setMealPlan({
      breakfast,
      lunch,
      dinner,
    });

    // Generate flavor text based on selected meals
    setFlavorText(generateFlavorText([...breakfast, ...lunch, ...dinner]));
  };

  const generateMealForMealType = (mealType, targetEnergy) => {
    const meal = [];
    let totalEnergy = 0;

    const pickRandomDish = (category) => {
      const dishes = mealDatabase[category];
      return dishes[Math.floor(Math.random() * dishes.length)]();
    };

    if (mealType === 'breakfast') {
      const breakfastDish = pickRandomDish('breakfast');
      const beverage = pickRandomDish('beverages');
      const fruit = pickRandomDish('Fruits');

      meal.push(breakfastDish, beverage, fruit);
      totalEnergy = breakfastDish.totalEnergy + beverage.totalEnergy + fruit.totalEnergy;
    } else {
      const starter = pickRandomDish('starters');
      const mainDish = pickRandomDish('mainDishes');
      const fruit = pickRandomDish('Fruits');
      const dessertOrCheese = Math.random() < 0.5 ? pickRandomDish('desserts') : pickRandomDish('cheeses');

      meal.push(starter, mainDish, fruit, dessertOrCheese);
      totalEnergy = starter.totalEnergy + mainDish.totalEnergy + fruit.totalEnergy + dessertOrCheese.totalEnergy;
    }

    // Adjust portion sizes to meet the energy goal
    adjustMealPortions(meal, targetEnergy, totalEnergy);

    return meal;
  };

  const adjustMealPortions = (meal, targetEnergy, totalEnergy) => {
    const adjustmentFactor = targetEnergy / totalEnergy;

    meal.forEach(dish => {
      dish.quantity *= adjustmentFactor;
      dish.totalEnergy = (dish.energyPer100g * dish.quantity) / 100;
    });
  };

  // Re-generate meal plan
  const handleRegenerateMeals = () => {
    generateMealPlan();
    // Scroll to the top of the page
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const generateFlavorText = (meals) => {
    const vitamins = new Set();
    const minerals = new Set();
    const proteinTypes = new Set();
    const lipidTypes = new Set();
    const glucidTypes = new Set();

    meals.forEach(meal => {
      meal.vitamins.forEach(vitamin => vitamins.add(vitamin));
      meal.minerals.forEach(mineral => minerals.add(mineral));
      proteinTypes.add(meal.proteinType);
      lipidTypes.add(meal.lipidType);
      glucidTypes.add(meal.glucidType);
    });

    return `Your meal plan is rich in vitamins such as ${[...vitamins].join(', ')}, and minerals including ${[...minerals].join(', ')}. 
    The meals provide a balanced intake of carbohydrates, proteins, and fats, primarily composed of ${[...glucidTypes].join(', ')}, 
    ${[...lipidTypes].join(', ')} and ${[...proteinTypes].join(', ')}. Enjoy a nutritious day!`;
  };

  // Utility function to format dish names
  const formatDishName = (name) => {
    if (!name) return "Fruit"; // Handle undefined names

    // Special case for "Fruit"
    if (name === "Fruit") return "Fruit";

    return name
      .replace(/([A-Z])/g, ' $1') // Add space before each capital letter
      .replace(/^./, (str) => str.toUpperCase()) // Capitalize the first letter
      .trim(); // Trim any leading or trailing spaces
  };

  return (
    <div className="container mx-auto px-4 py-8 bg-gradient-to-r from-green-100 to-blue-200 rounded-lg shadow-lg relative overflow-hidden">
      <div className="absolute inset-0 opacity-10 pointer-events-none">
        {/* Background image can be added here if desired */}
        <img src="https://source.unsplash.com/1600x900/?food" alt="" className="w-full h-full object-cover" />
      </div>
      <h1 className="text-4xl font-bold text-center mb-6 text-green-800 shadow-md p-2 rounded bg-white bg-opacity-90 border border-gray-300 relative z-10">
        Menu for You
      </h1>

      {mealPlan ? (
        <>
          <MealSection title="Breakfast" meals={mealPlan.breakfast} formatDishName={formatDishName} icon={<FaCoffee className="text-green-600" />} />
          <MealSection title="Lunch" meals={mealPlan.lunch} formatDishName={formatDishName} icon={<FaUtensils className="text-green-600" />} />
          <MealSection title="Dinner" meals={mealPlan.dinner} formatDishName={formatDishName} icon={<FaLeaf className="text-green-600" />} />

          <p className="mt-6 text-center text-gray-800 italic text-lg bg-gray-100 p-4 rounded-lg shadow-sm">{flavorText}</p>

          <div className="text-center mt-8">
            <button
              onClick={handleRegenerateMeals}
              className="bg-green-600 hover:bg-green-500 text-white font-bold py-2 px-6 rounded transition duration-300 shadow-lg transform hover:scale-105"
            >
              Re-Generate Meals
            </button>
          </div>
        </>
      ) : (
        <p className="text-center text-gray-700">Generating your meal plan...</p>
      )}
    </div>
  );
};

// Reusable component for displaying a meal section
const MealSection = ({ title, meals, formatDishName, icon }) => (
  <div className="mb-8 bg-white rounded-lg shadow-md p-4 border border-gray-200">
    <div className="flex items-center mb-4">
      {icon}
      <h2 className="text-4xl font-semibold ml-2 text-green-700">{title}</h2>
    </div>
    <ul className="list-disc list-inside space-y-2">
      {meals.map((meal, index) => (
        <li key={index} className="flex flex-col md:flex-row items-center p-2 rounded hover:bg-gray-100 transition duration-200">
          <span className="font-semibold text-lg text-green-600">{formatDishName(meal.name)}</span>: 
          <span className="ml-0 md:ml-2 text-gray-700">{meal.ingredients.join(', ')}</span>
          <span className="ml-0 md:ml-2 text-gray-500">({Math.round(meal.quantity)}g) - {Math.round(meal.totalEnergy)} kcal</span>
        </li>
      ))}
    </ul>
  </div>
);

export default GenerateMealsPage;
